### ISSUE TITLE
📖 Refactor Doc & Dockerization

### ISSUE THREAD

**Issue by aniruddha2000** [ArkaprabhaChakraborty/library-management-system#7]
Simplify the documentation & give users a simplified method of running the project.

- Keep docker-only instructions in the main README file and keep a separate doc folder and dump other methods there.
- Give a creation of superuser by `docker exec`
```bash
docker compose exec backend python manage.py createsuperuser
```
- It's not recommended to use makemigrations and migrate in the docker file as the responsibility of the image building process is to make the image ready and the developer has to create the migrations separately. For this, a good solution would be to have a Makefile in the project and use docker exec to hit the make target in the container.

cc @ArkaprabhaChakraborty 

TODO: 

- [x] Makefile and use migrate target to makemigrations and migrate DB
- [ ] Refactor Doc
- [ ] Add Makefile target to create a superuser

**Comment by ArkaprabhaChakraborty** [comment]
wait let me get the windows version up and running first. Then I'll apply the best practices in docker

**Comment by ArkaprabhaChakraborty** [comment]
```
Traceback (most recent call last):
lms-backend  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/utils.py", line 84, in _execute
lms-backend  |     return self.cursor.execute(sql, params)
lms-backend  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
lms-backend  |     return Database.Cursor.execute(self, query, params)
lms-backend  | sqlite3.OperationalError: no such table: auth_user
```

Currently resolving this.

**Comment by aniruddha2000** [comment]
Windows :)

**Comment by ArkaprabhaChakraborty** [comment]
Windows :)

**Comment by ArkaprabhaChakraborty** [comment]
Nope can't seem to solve this error, even after forcing migrations via the docker file django still can't find the necessary database tables.

**Comment by ArkaprabhaChakraborty** [comment]
I have added the db.sqlite3 and all migrations back to forcefully run the container on windows :). It runs now :). Now we can start the sanitization treatment of the repo. Apparently even after forcing "migrate" in the docker file, an empty db.sqlite3 file was being generated in the container which was causing the problem.

**Comment by ArkaprabhaChakraborty** [comment]
Now we need to diagnose the reason why the generated db was empty instead of being like the current one.. make docker and docker compose changes.. test .. ignore unnecessary files with proper usage of `.gitignore` and `.dockerignore` and finally move on to using Kubernetes.
